---
- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/psncius/docker-devops.git
      repository_path: /webapps/devops

  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - python-pip
        - nginx

    - name: Set timezone to Asia/Jakarta

      timezone:
        name: Asia/Jakarta

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'

    - name: Copy Upstart configuration
      template: src=devops-la-challenges.upstart.j2 dest=/etc/init/devops-la-challenges.conf

    - name: Make sure our server is running
      service: name=devops-la-challenges state=started

    - name: Copy Nginx site
      template: src=devops-la-challenges.nginx.j2 dest=/etc/nginx/sites-enabled/devops-la-challenges
      notify:
        - restart nginx

    - name: Remove any default sites
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service: name=nginx state=started


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
